### ISSUE TITLE
Making a planar selection 

### ISSUE THREAD

**Issue by BartBruininks** [LBT-CNRS/UnityMol-Releases#2]
Dear developers,

I am trying to use UnityMol for CG Martini systems and things are working pretty nice. However, I was wondering if it is possible to make a planar slice selection. I couldn't find it in the MDAnalysis selection syntax, but it is something I use a lot. I would like to a make a selection of the form:

resname W and x > 80

or even full plane equations in the form of:
resname W and (nx*(x-ox)+ny*(y-oy)+nz*(z-oz)-distance>0) 

Is there a way to do this in UnityMol atm?

Cheers,

Bart

**Comment by nezix** [comment]
Hi Bart,

In the next release (1.1.0), there will be a "inrect" keyword for the selection but you can indeed use coordinates to do it.

The keywords you are looking for are:
```prop x > 10.0```

You can do: 
```
resname W and prop x > 80
```
You can also combine those to do:
```
resname W and prop x > 80 and prop x < 100 and prop y > 0 and prop y < 10
```
For now, you cannot do arithmetic operations with selection properties.

Hope this helps,

Xavier

**Comment by BartBruininks** [comment]
That it does :)
