### ISSUE TITLE
Not finding MainUIScene.unity neither MainScene_VR_Desktop.unity files

### ISSUE THREAD

**Issue by Alex98156** [LBT-CNRS/UnityMol-Releases#3]
Hello, like the title says, i cannot. I've downloaded and install Github Desktop (i have understood that it comes with LFS), imported UnityMol-Release project in Unity 2019.4.32 (last). Then, i can't locate those files. Maybe i missed something. 

I'll be waiting for your reply and help. Regards.

**Comment by bam93** [comment]
Hi,

Thank you for your interest!
Sorry it took us a while to get the latest source code out. It just 
happened and you can find the release here:

https://github.com/LBT-CNRS/UnityMol-Releases/tree/1.0.36

Kind regards,
Marc



***@***.*** said:
>>Hello, like the title says, i cannot. I've downloaded and install
>>Github Desktop (i have understood that it comes with LFS), imported
>>UnityMol-Release project in Unity 2019.4.32 (last). Then, i can't
>>locate those files. Maybe i missed something. 

>>I'll be waiting for your reply and help. Regards.


-- 
 Dr. Marc Baaden  - Institut de Biologie Physico-Chimique, Paris
 ***@***.***      -      http://www.baaden.ibpc.fr
 FAX: +33 15841 5026  -  Tel: +33 15841 5176  ou  +33 609 843217
