### ISSUE TITLE
https://sourceforge.net/projects/unitymol/files/ does not provide a licence file

### ISSUE THREAD

**Issue by RubenGarcia** [LBT-CNRS/UnityMol-Releases#6]
https://sourceforge.net/projects/unitymol/files/
indicates
```
Copyright and License
License to be defined, it will be free for academic users.
```
so the download links from sourceforge cannot be used.
The same problem appears in
http://www.baaden.ibpc.fr/umol/

**Comment by bam93** [comment]
Thanks for pointing that out. Corrected on sourceforge. Also the sourcecode release (on github) comes with appropriate license file.
