### ISSUE TITLE
DllNotFoundException: Artemis on initiating IMD connection to NAMD 

### ISSUE THREAD

**Issue by ssateq** [LBT-CNRS/UnityMol-Releases#8]
![image](https://user-images.githubusercontent.com/72813792/178107191-642d2361-eafe-4a5c-86ab-df716d01886b.png)
Environment: UnityMol fixed_1.0.36, Unity Editor 2019.4.21f1, Windows 11

**Comment by HubLot** [comment]
Hi,

Thanks for reporting this issue. It looks like some external library files are missing in the repo.
I will fix this

**Comment by HubLot** [comment]
I just pushed a new commit containing the fix.
Could you try by downloading from the last commit? For the record, it fixes the issues on my side.
